# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
  facebook_app_id: "366193726893953"
  facebook_app_secret: "4c4cc00444b865299c8518e6869a92d8" 
  AWS_access_key_id: "AKIAIAGG6TUVXVRCHDCQ"
  AWS_secret_access_key: "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"
  fitbit_app_key: "60dbf4c7b3d64afca92a5949e7446f7c"
  fitbit_app_secret: "3d2cade2888f4272ba44da35cfb610b3"
  fitbit_app_key_test: "df79b1480da14daaace174cb04362bd0"
  fitbit_app_secret_test: "46b5b34e7338475fa65fdbeb1e137e1a"

production:
  facebook_app_id: "362740853905907"
  facebook_app_secret: "e95633669c57fd374b61e669d3dd7205"
  AWS_access_key_id: "AKIAIAGG6TUVXVRCHDCQ"
  AWS_secret_access_key: "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"
  fitbit_app_key: "60dbf4c7b3d64afca92a5949e7446f7c"
  fitbit_app_secret: "3d2cade2888f4272ba44da35cfb610b3"
  fitbit_app_key_test: "df79b1480da14daaace174cb04362bd0"
  fitbit_app_secret_test: "46b5b34e7338475fa65fdbeb1e137e1a"
  FITHUB_DATABASE_PASSWORD: "5-hTgDdz_WhPzEP6aZC7bg5voK"