# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
development:
  facebook_app_id: "366193726893953"
  facebook_app_secret: "4c4cc00444b865299c8518e6869a92d8" 
  AWS_access_key_id: "AKIAIMDFYRZUM4LBPL2Q"
  AWS_secret_access_key: "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"

production:
  facebook_app_id: "362740853905907"
  facebook_app_secret: "e95633669c57fd374b61e669d3dd7205"
  AWS_access_key_id: "AKIAIMDFYRZUM4LBPL2Q"
  AWS_secret_access_key: "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"
