development:
  adapter: postgresql
  database: fithub_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: fithub_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: fithub_production
  pool: 5
  timeout: 5000
